### ISSUE TITLE
Handle non-SemVer tags appropriately

### ISSUE THREAD

**Issue by nwiltsie** [uclahs-cds/tool-Docker-action#17]
https://github.com/uclahs-cds/docker-BCFtools-score contains multiple tools, so its tagged versions look like `v1.20_score-1.20-20240505`. Unfortunately with #14 I leaned in to the SemVer styling, so the metadata action [throws a fit](https://github.com/uclahs-cds/docker-BCFtools-score/actions/runs/9899322117/job/27347993207#step:3:158) over that non-standard tag:

```
Warning: v1.20_score-1.20-20240505 is not a valid semver. More info: https://semver.org/
Warning: No Docker image version has been generated. Check tags input.
Warning: No Docker tag has been generated. Check tags input.

ERROR: tag is needed when pushing to registry
```

We should be able to handle that case.

**Comment by nwiltsie** [comment]
Until I manage to get an appropriate global fix for this, individual repositories can work around this issue by passing `custom-tags`:

```yaml
jobs:
  push-or-delete-image:
    runs-on: ubuntu-latest
    name: Update GitHub Container Registry
    permissions:
      contents: read
      packages: write
    steps:
      - uses: uclahs-cds/tool-Docker-action@v2.0.0
        with:
          custom-tags: |
            type=match,pattern=v(.*),group=1
```
